source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '8.0'

pod 'AFNetworking', '~> 3.0'

pod 'AsyncDisplayKit'

#pod 'ReactiveCocoa'

use_frameworks!
pod 'Kingfisher', '~> 1.8'
pod 'SwiftyJSON', :git => 'https://github.com/SwiftyJSON/SwiftyJSON.git'